function newQuote() {
  var randomNumber = Math.floor(Math.random() * quotes.length);
  document.getElementById("quoteDisplay").innerHTML = quotes[randomNumber];
}

var quotes = [
  "1. At every doorway before you enter, you should take a good look around-- for you never know where your enemies might be seated within.",
  "2. Hail to a good host! A guest has come inside, where should he sit? He is impatient, stranding on the threshold, ready to try his luck.",
  "3. He needs fire, the one who has just come in, his knees are shivering. Food and dry clothes will do him well, after his journey over the mountains.",
  "4. He needs water, the one who has just arrived, dry clothes, and a warm welcome from a friendly host-- and if he can get it, a chance to listen and be listened to.",
  "5. A man needs wisdom if he plans to wander widely; life is easier at home. He'll be laughed at if he sits among the wise and has nothing to say.",
  "6. A wise man is not showy about his wisdom; he guards it carefully. He is silent when he comes to a stranger's home. The wise man seldom wanders into harm, for you can never have a more faithful friend than a good supply of wisdom.",
  "7. The watchful guest, when he arrives for a meal, should keep his mouth shut, listening with his ears and watching wit his eyes-- that's how the wise get wiser.",
  "8. A man is happy if he finds praise and friendship within himself. You can never be sure of where you stand in someone else's heart.",
  "9. A man is happy if he finds good advice within himself. Many men have received bad advice by trusting someone else.",
  "10.  A traveler cannot bring a better burden on the road than plenty of wisdom. It will prove better than money in an unfamiliar place— wisdom is the comfort of the poor.",
  "11. A traveler cannot bring a better burden on the road than plenty of wisdom, and he can bring no worse a burden than too much alcohol.",
  "12. There is not as much good as men claim there is in alcohol for one’s well-being. A man knows less as he drinks more, and loses more and more of his wisdom.",
  "13.  It’s as if a memory-stealing bird flies overhead while you drink, and steals your mind away. I myself have been trapped in that bird’s feathers, when I drank at Gunnloth’s home.",
  "14. I was drunk, I was too drunk, at Fjalar’s house. The best kind of feast is the one you go home from with all your wits about you.",
  "15. A noble man should be silent, thoughtful, and bold in battle. But every man should also be cheerful and happy, till the inevitable day of death.",
  "16. An unwise man thinks he’ll live forever if only he can avoid a fight, but old age will give him no peace, even if weapons do.",
  "17. A foolish man misuses his mouth— he talks too much, or says nothing. As soon as he gets a drink, he’ll say anything he knows.",
  "18. Only a man who is wide-traveled and has wandered far can know something about how other men think. Such a man is wise.",
  "19. Don’t hold on to the mead-horn, but drink your fair share. Say something useful or stay quiet. And no one else will judge you poorly if you go to sleep early.",
  "20. A gluttonous man, unless he watches himself, will eat to his own detriment. Wise men will often ridicule a fool on account of his belly.",
  "21. Even cows know when they should go home and leave behind the fields, but an unwise man does not know the measure of his own appetite.",
  "22. A stupid man and an undisciplined one laughs at everything. He hasn’t learned a lesson that would do him good: he himself isn’t flawless.",
  "23. A fool stays awake all night worrying about everything. He’s fatigued when the morning comes, and his problems remain unsolved.",
  "24. An unwise man thinks anyone who laughs with him is his friend. He doesn’t understand that the wise are mocking him, even when he overhears them.",
  "25. An unwise man thinks anyone who laughs with him is his friend, but he won’t find these friends when he goes to court— no one will speak on his behalf.",
  "26. A stupid man thinks he knows everything if he gets himself in a tough corner. But he doesn’t even know what he’ll answer, if men ask him questions.",
  "27. It’s best for a fool to keep his mouth shut among other people. No one will know he knows nothing, if he says nothing. Ill-informed people are also the ones who don’t know when to stop talking.",
  "28. You will seem wise if you know the answer, and know how to explain it. People are not able to keep a secret of what they of what they hear about other people.",
  "29. You will hurt yourself with all your talking if you never close your mouth. A hasty tongue, unless it’s disciplined, often earns its owner punishment.",
  "30. No one should ridicule anyone else, even if he owes him money. Many a man seems wise if he is never questioned, but he may prove otherwise.",
  "31. A man may seem wise if he pokes fun at another when the other man is away. But the man who talks behind another man’s back is a fool, even if his listeners laugh.",
  "32. Many men are kind, but can be driven to fight. There will always be conflict between men: where there’s more than one, there’s a fight.",
  "33. You should eat your meals early, unless you’re visiting a friend. A hungry man sits and gets sluggish, and his wits are impaired.",
  "34. It’s a long and crooked walk to a bad friend, even if he lives nearby. But it’s an easy road to a good friend, no matter how long the journey.",
  "35. You should keep moving. You should never be a guest forever in any one place. Your welcome will wear out if you stay too long beneath another’s roof.",
  "36. It’s better to have a home, even if it’s little— everyone should call somewhere “home.” Even if you own just two goats beneath a faulty roof, that’s still better than begging.",
  "37. Better to have a home, even if it’s little— everyone should call somewhere “home.” Your heart will be wounded if you have to beg for every meal from somebody else.",
  "38. Never go even a single step without a weapon at your side; you never know when you might find yourself in need of a spear.",
  "39. I have never met a man so generous nor so hospitable that he would not welcome repayment, nor have I met a mans o giving that he’d turn down a thing offered in return.",
  "40. Do not be so sparing in using your money that you don’t use it for your own needs. Often what you save for your children will end up in the hands of your enemies— many things will go worse than you expect.",
  "41. Friends should provide their friends with weapons and clothing; this kind of generosity shows. Generous mutual giving is the key to lifelong friendship.",
  "42. Be a friend to your friend, and repay each gift with a gift. Repay laughter with laughter, repay treachery with treachery.",
  "43. Be a friend to your friend and also to his friend, but never be a friend to the enemy of your friend.",
  "44. If you have a good friend, and really trust him, and want good to come of your friendship, you should speak your mind with him, exchange gifts, visit him often.",
  "45. But if you have another friend, and you mistrust him but want to benefit from him, nonetheless— you should speak to him kindly, flatter him, and repay his treachery with your own.",
  "46. This same friend, if you mistrust him, and suspect him to be false in his words: you should talk with him, laugh with him, but repay just what he gives you.",
  "47. I was young once, I walked alone, and I became lost on my way. I felt like I was rich when I met another traveler— people’s joy is in other people.",
  "48. Kind, brave people live best, they never nurture a grudge. It’s unwise to spend your life worrying, dreading your responsibilities.",
  "49. I gave my clothes to two scarecrows, once when I walked in a field. They thought they were human as soon as they had clothes on; a naked man feels ashamed.",
  "50. A fir-tree decays, standing over a farm, no longer protected by bark and needles. A person is the same way if nobody loves him; how will he live much longer?",
  "51. The friendship among false friends burns warmly for five days, but then it’s extinguished by the sixth day, and the friendship is over.",
  "52. You should not give only big gifts; often a little thing will win you favor. I have won friends with just half a loaf of bread and a bowl of soup.",
  "53. Where the beaches are small, it’s a small sea that washes them— and so it is with little minds. Not everyone is equally wise, but the average is moderately wise.",
  "54. You should be only a little wise, never too wise. The happiest people throughout their lives are the moderately wise.",
  "55. You should be only a little wise, never too wise. A wise man’s heart is seldom glad if he’s truly wise.",
  "56. You should be only a little wise, never too wise. It’s best not to know your fate beforehand; you’ll live happier if you don’t.",
  "57. A torch is lit by another and burns till it’s burned out; a fire is kindled by another fire. A man becomes wise by speaking with other men, but foolish by keeping to himself.",
  "58. Rise early, if you want to take another man’s property, or his life. A sleeping wolf seldom wins a sheep, or a sleeping warrior a victory.",
  "59. Rise early if you have no one to work for you, and get straight to work. You lose more than time if you sleep when it dawns; for the early riser, wealth is half-won.",
  "60. You should know how to dry logs for firewood and bark for roofing, and also this: how to measure time and the seasons.",
  "61. You should always go out with your hair combed and a meal in your belly, even if you can’t afford good clothes. You should not be ashamed of your shoes and pants nor of your horse, even if it’s not a good one.",
  "62. A hungry eagle snaps his beak and stretches out his neck, when the sea comes into sights. People get the same look about them when they walk among strangers and have no one to speak well of them.",
  "63. If you want to be called wise, you should know how to ask and answer wisely. Tell your secret to one person, never to two— everyone knows, if three people know.",
  "64. A wise man should use his abilities only in moderation. Otherwise, when he is in battle, he’ll learn that no one is bravest of all.",
  "65. You will often get repayment in kind for the words you speak to others.",
  "66. I have come too early to some events and too late to others. The drinks were all gone, or else not even made; a hated man gets little hospitality.",
  "67. Now and then I’ve been invited to a friend’s home, as long as I had no need for food, or as long as I could make my inhospitable host’s cellars fuller rather than emptier.",
  "68. Fire is best for mortals, and sunshine— and also good health, if you have it, and living beyond reproach.",
  "69. No one is totally wretched, even if his health is bad— some find happiness in their children, some in their kin, some in their money, some in work well done.",
  "70. Better to be alive, no matter what, than dead— only the living enjoy anything. I saw a rich man’s house, but it was on fire, and he lay dead outside the door.",
  "71. A limping man can ride a horse, a handless man can herd, a deaf man can fight and win. It’s better even to be blind than fuel for the funeral pyre; what can a dead man do?",
  "72. Better to have a son than not, even if he’s born late in life, even if he’s born after you die. You’ll rarely see memorials or graves standing near the road that were raised for men without sons.",
  "73. Two men will defeat one; your tongue can endanger your head. In every hand hidden by a cloak, I expect to see a weapon.",
  "74. The seaman is glad at evening, looking forward to his dinner, with just a short distance to row home. But an autumn night is untrustworthy. Many things can get worse in only five days, and even more in a month.",
  "75. The ignorant man does not know how little he knows. You become foolish by listening to fools. One man is rich, another man is poor, neither has the other to blame.",
  "76. Cows die, family die, you will die the same way. But a good reputation never dies for the one who earns it well.",
  "77. Cows die, family die, you will die the same way. I know only one thing that never dies: the reputation of one who’s died.",
  "78. I saw big hearts of cattle owned by a rich man’s sons; now they carry a beggar’s staff. Wealth is like the twinkling of an eye— no friend could be more faithless.",
  "79.  If an unwise man chances upon money or a woman’s love, he will grow more arrogant but not more intelligent; he will be deceived about his own worth.",
  "80. What you ask of the runes will prove true; they are gifts of the Aesir, made by the gods and painted by Odin. You’ll learn best with your mouth shut.",
  "81. Don’t praise the day until it’s night, don’t praise your wife until she’s buried, don’t praise the sword till after the fight, nor your daughter till she’s married, don’t praise the ice until it’s crossed, nor the ale until you’re sloshed.",
  "82. Chop wood when the wind blows, row your boat on the sea, court a lover at nighttime (for the day has many eyes). Value a ship for its speed, a shield for protection, a sword for its sharpness, and a woman for her kiss.",
  "83. Drink ale by the fire, skate on the ice, buy a thin horse and a rusty sword. Give your horse food and let your dog feed itself.",
  "84. No man should trust the words of a girl, nor anything a woman says. Women’s hearts are molded on a wobbly wheel. Deception lurks in their words.",
  "85.  A breaking bow, a burning fire, a howling wolf, a cawing crow, a grunting pig, a rootless tree, a swelling wave, a boiling kettle, (86) a flying spear, a crashing wave, one-night-old ice, a striped snake, the words of a bride in bed, a broken sword, a playful bear, the child of a king, (87)  a sick calf, a stubborn servant, a prophet who foresees good things, a corpse on the battlefield, your brother’s killer (even if you meet him public), a half-burned house, a horse that’s too fast (remember, a horse is unusable if only one foot breaks)— may you never be so trusting that you trust all these things.",
  "89. Do not put too much trust in your newly planted crops, nor in your child too early— weather will shape the field and whim will shape the child, and neither will stay the same.",
  "90. Take care not to love a deceitful woman, it is like driving an unshod horse, a playful, young, poorly-tamed foal, across slippery ice, or like sailing a ship in a wild wind, or trying to catch a reindeer on foot after the mountains thaw.",
  "91. I’ll speak plainly now, since I know both men and women: men lie to women. We speak most eloquently when we tell the biggest lies, and seduce even wise women with lies.",
  "92. A man should speak eloquently and offer gifts to a woman whose love he wants. Praise the body of a beautiful woman; you will win her if you praise her.",
  "93. No man should mock another for falling in love. Love-sickness often strikes harder on a wise man than a fool.",
  "94. No man should mock another for falling in love; love is strong enough to make a fool out of a man who once was wise.",
  "95. Only you know what dwells in your heart when you are alone; but nothing is worse for a wise person than to have nothing to love.",
  "96. I experienced this when I waited among the reeds and my lover did not come to me. That wise girl was my flesh and my heart, though I could not call her my own.",
  "97. I found Billing’s daughter, fair as a sun-ray, asleep on her bed. The life of a lord seemed as nothing to me unless I could live with that woman.",
  "98. 'You should come back in the evening, Odin,' she said, 'if you want to woo me— it is improper for others to know of such a scandal'.",
  "99. I turned back, and thought that I would win her. I imagined that I would win the woman’s love and all her joy.",
  "100. But when I came back that night, there was a good company of warriors awake and ready for me. With burning flames and torches held high, I was shown my miserable way out.",
  "101. And when morning came, and I returned, everyone in the hall was sleeping— and then I found a watchdog tied to the bed of that good woman.",
  "102. There’s many a good woman, if you get to know her, who’ll change her mind about a man; I learned that when I tried to seduce a wise woman. That lady showed me every kind of shame, and I gained no wife for my trouble.",
  "103. If you want to be very wise, be happy at home and cheerful with a guest. Cultivate wisdom, a good memory, and eloquence, and speak kind words often. You’ll be called a fool if you can’t say much — that’s the mark of the unwise.",
  "104. I visited an old giant, and now I’ve returned. I didn’t stay silent there. I spoke many words in support of my cause at Suttung’s hall.",
  "105. Gunnloth, his daughter, gave me a drink of his precious mead while I sat on a golden chair. I would later give her a bad repayment for her trusting mind, for her troubled mind. ",
  "106. Giants’ dwellings were over and under me. I used Rati’s tusk to burrow out and gnaw away the rock— in this way, I got out with my head.",
  "107. I made good use of the disguise I used; few things are too difficult for the wise. Now Othrerir is rescued from the clutches of the giants.",
  "108. I doubt I could have escaped Jotunheim if I hadn’t used Gunnloth, the good woman who rested in my arms."
  "109. The next day the frost-giants came to ask news about Odin in Odin’s hall; they inquired about that evildoer, whether he was among the gods, or whether Suttung had killed him.",
  "110. I believe that Odin swore an oath to them— but who can trust Odin? He left Suttung deceived in his own home, and he left Gunnloth weeping.",
  "111. It is time to speak on the wise man’s chair at Urth’s well. I saw and was silent, I saw and I thought, I listened to men’s speech. I heard about runes, they were not silent with counsel at Odin’s hall, in Odin’s hall, I heard them say so:",
  "112. I counsel you Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you can remember it: Do not rise at night, unless you’re spying on your enemies, or seeking a place to relieve yourself.",
  "113. I counsel you Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you can remember it: Do not sleep in the arms of a sorceress, or else she will lock your limbs.",
  "114. She will enchant you so that you won’t care for advice nor a powerful man’s words; you will want neither food nor the pleasure of friends’ company, and you will sleep full of sorrow.",
  "115. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Never seduce another man’s woman with whispers in her ear.",
  "116. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: If you spend time wandering by land or by sea, bring plentiful provisions.",
  "117. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Never let a bad man know of your misfortune, for you will never profit at all for telling him about it.",
  "118. I saw a bad woman’s words bite a man in the neck— a lying tongue was his death, and not even with good cause.",
  "119. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: If you have a friend, and you trust him, go and visit him often. Weeds and high grass will grow on a path that nobody travels.",
  "120. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Get a good man to teach you the runes, and learn a healing spell while you live.",
  "121. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Never be the first to break friendship with your friend. Sadness will eat up your heart if you have no one you can talk to.",
  "122. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: You should never exchange words with someone who won’t see reason.",
  "123. You will never get a reward for speaking with a bad man, but a good man will make you happy with his praise.",
  "124. Men become friends when they can share their minds with one another. Anything is better than being lied to: a real friend will disagree with you openly.",
  "125. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Don’t speak even three words with a man worse than you. Often the better man will lose when a worse man fights him.",
  "126. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Don’t make shoes, and don’t make weapons, except for yourself; if there’s a flaw in the shoe, or the spearshaft is crooked, your name will be cursed.",
  "127. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: When you are at war, call it war, and give your enemies no peace.",
  "128. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Never be glad to hear bad news, but be cheerful about good news.",
  "129. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: You should never look when when you’re in a fight— men who do so may get turned to stone— beware, or someone may curse you.",
  "130. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: If you want to win a good woman, speak cheerfully with her, and enjoy it while you do, make promises to her, and keep your promises, you’ll never regret winning such a prize.",
  "131. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: I advise you to be wary, though never fearful: be most wary about drinking, about other men’s women, and about a third thing: about men and their temptation to steal.",
  "132. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Never mock, never laugh at, a guest nor a wanderer.",
  "133. Those inside the house rarely know anything about the stranger who knocks at their door, but there is no man so good that he has no flaw, nor a man so bad he’s good for nothing.",
  "134. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Never laugh at an old man. There is often wisdom in what old men say; wise words will often come from a gray-bearded mouth. From those who hang with dried skins, those who swing with dried skins, those who wave with dried skins.",
  "135. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: Never spite a guest nor be stingy with your food— treat a poor wanderer well.",
  "136. Otherwise it’s a bitter tree you’ll find yourself hanging from in the sight of all. Give a beggar something, or he will call a curse down on your every limb.",
  "137. I counsel you, Loddfafnir, if you’ll take my advice, you’ll profit if you learn it, it’ll do you good if you remember it: When you drink beer, choose the might of the earth, for the earth is good against beer, and fire against sickness, oak against an irritable bowel, wheat against magic, an elder-tree against family quarrels, maggots against venomous bites, runes against distress, ground against water. Swear your hate beneath the moon.",
  "138. I know that I hung on a wind-battered tree nine long nights, pierced by a spear and given to Odin, myself to myself, on that tree whose roots grow in a place no one has ever seen.",
  "139. No one gave me food, no one gave me drink. At the end I peered down, I took the runes— screaming, I took them— and then I fell.",
  "140. I learned nine spells from the famous son of Bolthorn, the father of Bestla, and I won a drink of that precious mead, poured from Othrerir.",
  "141. My imagination expanded, I became wise, I grew, and I thrived. One word chased another word flowing from my mouth, one deed chased another deed flowing from my hands.",
  "142. You will find runes, runic letters to read, very great runes, very powerful runes, which Odin painted, and which the holy gods made, and which Odin carved.",
  "143. Odin carved for the gods, and Dain for the elves, Dvalin for the dwarves, and Asvith for the giants; I carved some myself.",
  "144. Do you know how to write them? Do you know how to read them? Do you know how to paint them? Do you know how to test them? Do you know how to ask them? Do you know how to bless them? Do you know how to send them? Do you know how to offer them?",
  "145. It is better not to pray at all than to pray for too much; nothing will be given that you won’t repay. It is better to sacrifice nothing than to over too much. Odin carved this before the birth of humankind, when he rose up and returned again.",
  "146. I know magic spells that no woman knows and no man, either. The first is called “Help,” and it will help you in lawsuits and sadness, and all kinds of worries.",
  "147. I know a second spell which men need if they want to heal others.,"
  "148. I know a third spell; if I have a great need to thwart my enemies, I dull the edges of their weapons, and none of their blades will bite.",
  "149. I know a fourth spell; if chains and locks are placed upon my limbs, I cast this spell so that I can escape. The chains burst from my hands, the locks burst from my feet.",
  "150. I know a fifth spell; if I see a spear cast into a crowd of battling foes, it cannot fly so fast that I can’t change its course as long as I can see it.",
  "151. I know a sixth spell; if a man carves a curse against me in runes on the root of a tree, I call this spell down upon that man, and his curse harms him instead of me.",
  "152. I know a seventh spell; if I see a great flame consuming a hall full of people, it cannot burn so bright that I cannot save those inside; I know how to cast this spell.",
  "153. I know an eighth spell; it would be useful for anyone to learn it. When hate arises between any two people, I can cool their tempers.",
  "154. I know a ninth spell; if the need arises for me to save a ship upon the sea, I can calm the wind upon the waves and soothe the sea to sleep.",
  "155. I know a tenth spell; if I see witches at play in the air, I can cast this spell so that they get lost, so they can’t find their skins, so they can’t find their minds.",
  "156. I know an eleventh spell; if I lead old friends into a battle, I enchant their shields so that they will have the victory; and return from battle unharmed. They will come home without harm.",
  "157. I know a twelfth spell; if I see, hanging from a tree, a dead man’s corpse, I carve some runes and paint them, and then that corpse will walk and speak with me.",
  "158. I know a thirteenth spell; if I sprinkle water upon a new-born boy, he will never be killed even if he goes into battle; that man will not die from violence.",
  "159. I know a fourteenth spell; it allows me to count all the gods for men. I know the names of all the gods and elves, and few who are fools can say that.",
  "160. I know a fifteenth spell; the dwarf Thjothreyrir cast it upon Delling’s doors. He conjured power the gods, and courage for the elves; they knew Odin.",
  "161. I know a sixteenth spell; if I want to win over a cunning woman and have her all to myself, I can change the mind of that lovely-armed beauty and win her favor for myself.",
  "162. I know a seventeenth spell, to prevent a beautiful woman from shunning me. Loddfafnir, all these spells would be useful to you all your life. They would profit you if you learned them, they’d do you good if you remembered them, they’d suit your needs if you could use them.",
  "163. I know an eighteenth spell which I will never teach to a girl or a woman, unless maybe to the one I call my wife, or my sister. It is much better that one alone should know this, which is the last of the spells.",
  "164. Now the words of the One-Eyed are heard in Valhalla, for the benefit of humans, for the harm of giants; health to you who speak them, health to you who know them, joy to you who learn them, health to you who hear them."

];
